#!/bin/sh

set -e

"$ZIG_DOCGEN" zig src/download/0.6.0/release-notes.html www/download/0.6.0/release-notes.html
rm a.txt b.txt hello.txt # garbage created by building release notes
"$ZIG_DOCGEN" zig src/index.html www/index.html
