#!/bin/sh

set -e

export ZIG_DOCGEN="/home/andy/tmp/docgen"
"$ZIG_DOCGEN" zig src/download/0.7.0/release-notes.html www/download/0.7.0/release-notes.html
#"$ZIG_DOCGEN" zig src/index.html www/index.html
