#!/bin/bash

set -x

pandoc www/documentation/index.md \
    -f markdown_github+header_attributes+grid_tables+backtick_code_blocks+fenced_code_attributes+raw_html-hard_line_breaks \
    -T 'Documentation - The Zig Programming Language' \
    --toc --toc-depth=4 -R -Ss --no-highlight --normalize \
    -H www/documentation/header.html -t html5 -o www/documentation/index.html

# toc adds the actual header which we don't want
sed -i '/li.*Zig Documentation.*ul/d' www/documentation/index.html
