#!/bin/sh

set -e

rm -f www/download/index.html
rm -f www/download/index.json
s3cmd sync -P -v --no-preserve --no-mime-magic --add-header="Cache-Control: max-age=0, must-revalidate" www/ s3://ziglang.org/
