#!/bin/sh

set -e

~/dev/zig/build/bin/zig test ~/dev/zig/lib/std/std.zig -femit-docs --output-dir www/documentation/master/std/ -fno-emit-bin
mv www/documentation/master/std/docs/* www/documentation/master/std/
rmdir www/documentation/master/std/docs

sed -i '6 a <link rel="search" href="opensearch.xml" type="application/opensearchdescription+xml" title="Zig Standard Library Documentation Search">' www/documentation/master/std/index.html

#s3cmd sync -P --no-preserve --no-mime-magic --add-header="Cache-Control: max-age=0, must-revalidate" ~/dev/zig/build/zig-cache/docs/ s3://ziglang.org/documentation/master/std/
